<?php

namespace Frontend\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LikeableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeableRepository extends EntityRepository
{
}
