frontend_admin_articles:
    resource: "@FrontendBundle/Resources/config/routing/article.yml"
    prefix:   /admin/articles

frontend_admin_medias:
    resource: "@FrontendBundle/Resources/config/routing/media.yml"
    prefix:   /admin/medias

frontend_admin_groups:
    resource: "@FrontendBundle/Resources/config/routing/group.yml"
    prefix:   /admin/groups

frontend_admin_users:
    resource: "@FrontendBundle/Resources/config/routing/user.yml"
    prefix:   /admin/users



locale_language:
    path:     locale/{locale}
    defaults: { _controller: FrontendBundle:Language:locale }
    #schemes:  [https]
admin_homepage:
    path:     /admin
    defaults: { _controller: FrontendBundle:Admin:index }




addCommentArticle:
    path:    /addCommentArticle/{id}
    defaults: { _controller: FrontendBundle:Default:addCommentArticle }
    methods:  [POST]
    options:
      expose: true

addLikeArticle:
    path:    /addLikeArticle/{id}
    defaults: { _controller: FrontendBundle:Default:addLikeArticle }
    methods:  [GET]
    options:
      expose: true

homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Default:index }

oneArticle:
    path:     /article/{slug}.html
    defaults: { _controller: FrontendBundle:Default:oneArticle }
