services:
  # services to fetch online users
  activity_listener:
    class: Frontend\FrontendBundle\Listener\ActivityListener
    arguments: [@security.context, @doctrine.orm.entity_manager]
    tags:
      - {name:kernel.event_listener, event:kernel.controller, method:onCoreController}
  # service to count number of login
  login_listener:
    class: Frontend\FrontendBundle\Listener\LoginListener
    arguments: ['@fos_user.user_manager']
    tags:
      - { name: 'kernel.event_listener', event: 'security.interactive_login' }
      - { name: 'kernel.listener', event: 'fos_user.security.implicit_login' }
